# TCL File Generated by Component Editor 18.1
# Sat Jun 06 04:19:58 NZST 2026
# DO NOT MODIFY


# 
# avalon_noc_adapter_pd "Avalon NoC Adapter" v1.0
# COMPSYS 701 team 2026.06.06.04:19:58
# Nios II Avalon-MM bridge to the TDMA-MIN NoC
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_noc_adapter_pd
# 
set_module_property DESCRIPTION "Nios II Avalon-MM bridge to the TDMA-MIN NoC"
set_module_property NAME avalon_noc_adapter_pd
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "COMPSYS 701"
set_module_property AUTHOR "COMPSYS 701 team"
set_module_property DISPLAY_NAME "Avalon NoC Adapter"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_noc_adapter_pd
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file asp_packet_pkg.vhd VHDL PATH ../../common/asp_packet_pkg.vhd
add_fileset_file TdmaMinTypes.vhd VHDL PATH ../../common/TdmaMinTypes.vhd
add_fileset_file avalon_noc_adapter.vhd VHDL PATH avalon_noc_adapter.vhd
add_fileset_file avalon_noc_adapter_pd.vhd VHDL PATH avalon_noc_adapter_pd.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL avalon_noc_adapter_pd
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file asp_packet_pkg.vhd VHDL PATH ../../common/asp_packet_pkg.vhd
add_fileset_file TdmaMinTypes.vhd VHDL PATH ../../common/TdmaMinTypes.vhd
add_fileset_file avalon_noc_adapter.vhd VHDL PATH avalon_noc_adapter.vhd
add_fileset_file avalon_noc_adapter_pd.vhd VHDL PATH avalon_noc_adapter_pd.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges BOTH
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avs
# 
add_interface avs avalon end
set_interface_property avs addressUnits WORDS
set_interface_property avs associatedClock clock
set_interface_property avs associatedReset reset
set_interface_property avs bitsPerSymbol 8
set_interface_property avs burstOnBurstBoundariesOnly false
set_interface_property avs burstcountUnits WORDS
set_interface_property avs explicitAddressSpan 0
set_interface_property avs holdTime 0
set_interface_property avs linewrapBursts false
set_interface_property avs maximumPendingReadTransactions 0
set_interface_property avs maximumPendingWriteTransactions 0
set_interface_property avs readLatency 0
set_interface_property avs readWaitStates 0
set_interface_property avs readWaitTime 0
set_interface_property avs setupTime 0
set_interface_property avs timingUnits Cycles
set_interface_property avs writeWaitTime 0
set_interface_property avs ENABLED true
set_interface_property avs EXPORT_OF ""
set_interface_property avs PORT_NAME_MAP ""
set_interface_property avs CMSIS_SVD_VARIABLES ""
set_interface_property avs SVD_ADDRESS_GROUP ""

add_interface_port avs avs_address address Input 3
add_interface_port avs avs_read read Input 1
add_interface_port avs avs_write write Input 1
add_interface_port avs avs_writedata writedata Input 32
add_interface_port avs avs_readdata readdata Output 32
set_interface_assignment avs embeddedsw.configuration.isFlash 0
set_interface_assignment avs embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs embeddedsw.configuration.isPrintableDevice 0


# 
# connection point irq
# 
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint avs
set_interface_property irq associatedClock clock
set_interface_property irq associatedReset reset
set_interface_property irq bridgedReceiverOffset ""
set_interface_property irq bridgesToReceiver ""
set_interface_property irq ENABLED true
set_interface_property irq EXPORT_OF ""
set_interface_property irq PORT_NAME_MAP ""
set_interface_property irq CMSIS_SVD_VARIABLES ""
set_interface_property irq SVD_ADDRESS_GROUP ""

add_interface_port irq irq irq Output 1


# 
# connection point noc_send
# 
add_interface noc_send conduit end
set_interface_property noc_send associatedClock ""
set_interface_property noc_send associatedReset ""
set_interface_property noc_send ENABLED true
set_interface_property noc_send EXPORT_OF ""
set_interface_property noc_send PORT_NAME_MAP ""
set_interface_property noc_send CMSIS_SVD_VARIABLES ""
set_interface_property noc_send SVD_ADDRESS_GROUP ""

add_interface_port noc_send noc_send_addr addr Output 8
add_interface_port noc_send noc_send_data data Output 32


# 
# connection point noc_recv
# 
add_interface noc_recv conduit end
set_interface_property noc_recv associatedClock ""
set_interface_property noc_recv associatedReset ""
set_interface_property noc_recv ENABLED true
set_interface_property noc_recv EXPORT_OF ""
set_interface_property noc_recv PORT_NAME_MAP ""
set_interface_property noc_recv CMSIS_SVD_VARIABLES ""
set_interface_property noc_recv SVD_ADDRESS_GROUP ""

add_interface_port noc_recv noc_recv_addr addr Input 8
add_interface_port noc_recv noc_recv_data data Input 32

