-- ============================================================================
-- ReCOP_PM.vhd  –  Program Memory (ROM)  [DE2-115 / Cyclone IV E]
--
-- Capacity   : 512 words × 32 bits  (fits in 2 × Cyclone IV E M9K blocks)
-- Technology : Altera altsyncram, ROM mode, Cyclone IV E (EP4CE115F29C7)
-- Read       : synchronous, 1-clock latency
-- Init file  : program.mif  (generated by recop_asm.py assembler)
--
-- External interface:
--   clock  in  std_logic                     system clock (50 MHz DE2-115)
--   addr   in  std_logic_vector(8 downto 0)  9-bit word address (PC[8:0])
--   instr  out std_logic_vector(31 downto 0) 32-bit instruction word
--
-- Usage as a component:
--   pm : entity work.ReCOP_PM
--       port map (clock => clk, addr => pc(8 downto 0), instr => ir);
-- ============================================================================

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

library altera_mf;
use altera_mf.all;

entity ReCOP_PM is
    port (
        clock : in  std_logic;
        addr  : in  std_logic_vector(8 downto 0);
        instr : out std_logic_vector(31 downto 0)
    );
end entity ReCOP_PM;

architecture Behavior of ReCOP_PM is

    component altsyncram
    generic (
        address_aclr_a         : string;
        clock_enable_input_a   : string;
        clock_enable_output_a  : string;
        init_file              : string;
        intended_device_family : string;
        lpm_hint               : string;
        lpm_type               : string;
        numwords_a             : natural;
        operation_mode         : string;
        outdata_aclr_a         : string;
        outdata_reg_a          : string;
        widthad_a              : natural;
        width_a                : natural;
        width_byteena_a        : natural
    );
    port (
        clock0    : in  std_logic;
        address_a : in  std_logic_vector(8 downto 0);
        q_a       : out std_logic_vector(31 downto 0)
    );
    end component;

begin

    pm_core : altsyncram
    generic map (
        address_aclr_a         => "NONE",
        clock_enable_input_a   => "BYPASS",
        clock_enable_output_a  => "BYPASS",
        init_file              => "program.mif",
        intended_device_family => "Cyclone IV E",
        lpm_hint               => "ENABLE_RUNTIME_MOD=NO",
        lpm_type               => "altsyncram",
        numwords_a             => 512,
        operation_mode         => "ROM",
        outdata_aclr_a         => "NONE",
        outdata_reg_a          => "UNREGISTERED",
        widthad_a              => 9,
        width_a                => 32,
        width_byteena_a        => 1
    )
    port map (
        clock0    => clock,
        address_a => addr,
        q_a       => instr
    );

end architecture Behavior;
